# answers to expect
string[] person         # e.g. ['John', 'Alex', 'Tom']
string[] object         # e.g. ['Book', 'Cup', 'Sponge']
string[] drink          # e.g. ['Coke', 'Beer', 'Coffee']
string[] location       # e.g. ['Living room', 'Bedroom', 'Kitchen']
string[] action         # e.g. ['Go', 'Take', 'Give']
std_msgs/Bool ack       # e.g. True (wait for a yes/no answser with variants like 'okay', 'ok', ...